version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-api-python-client
    versions:
    - 1.12.8
    - 2.0.2
    - 2.1.0
    - 2.2.0
  - dependency-name: google-cloud-storage
    versions:
    - 1.35.0
    - 1.35.1
    - 1.36.0
    - 1.36.1
    - 1.36.2
    - 1.37.0
    - 1.37.1
  - dependency-name: httplib2
    versions:
    - 0.18.0
