version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          GOOGLE_APPLICATION_CREDENTIALS_FOR_TEST: /tmp/google-account-credential-for-test.json


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install pip-tools
            make setup

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: check requirements.txt
          command: |
            . venv/bin/activate

            make build
            git diff --exit-code

      - run:
          name: prepare credentials for testing
          command: |
            echo "${GOOGLE_APPLICATION_CREDENTIAL_PAYLOAD}" > $GOOGLE_APPLICATION_CREDENTIALS_FOR_TEST

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports
